name: Proxy Cleanup

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  Main-Job:
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_SSH_KEY_CONTENT: ${{ secrets.OCI_SSH_KEY_CONTENT }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.7
        with:
          ref: 'workspace'

      - name: cleanup
        id: cleanup
        uses: ramSeraph/oci-simple-proxy-action/cleanup@v0.0.1
        with:
          oci-compartment-name: ${{ secrets.OCI_COMPARTMENT_NAME }}
          max-duration-secs: 36000
