name: Telangana Government Order Issue Registry archiver

concurrency: 
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  Run:
    if: github.repository == 'ramSeraph/egazette'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - name: Pull and Push call
        uses: ./.github/actions/common/
        with:
          source: 'telangana_goir'
          ia_access_key: ${{ secrets.IA_ACCESS_KEY }}
          ia_secret_key: ${{ secrets.IA_SECRET_KEY }}
